#!/usr/bin/env sh

# Set location for extracted frames
loc=/tmp/frames

# Save PID to file
PID="/tmp/livewall.pid"

# Set default values for image type and frame interval
type=jpg
nth_frame=20

# Define function to start livewall
start() {
  stop >/dev/null 2>&1 # Stop any instances running

  rm -rf "$loc" # Remove any existing frames directory

  if [ -e "$1" ]; then
    mkdir "$loc" # Create frames directory

    echo "Extracting frames from '$1'..."
    ffmpeg -i "$1" -r "$nth_frame" "$loc/%d.$type" >/dev/null 2>&1 # Extract frames
    set "$loc" & # Start setting wallpapers

    echo "$!" > "$PID" # Save PID to file
    echo "Livewall started successfully!"
  else
    echo "Please provide a video file."
  fi
}

# Define function to stop livewall
stop() {
  if [ -e "$PID" ]; then
    kill -9 "$(cat "$PID")" >/dev/null 2>&1 # Kill process and remove PID file
    echo "Livewall stopped successfully!"
    rm -rf "$PID"
  else
    echo "No livewall instance is running!"
  fi
}

# Define function to set wallpapers
set_wallpapers() {
  if [ "$(ls "$1"/ | wc -l)" != 0 ]; then # Check if any frames were extracted
    i=1
    while true; do
      feh --bg-fill "$1/$i.$type" # Set wallpaper
      i=$((i+1))
      if [ "$i" -eq "$(ls "$1"/ | wc -l)" ]; then
        i=1
      fi
    done
  else
    echo "Failed to find extracted images in '$1'!"
  fi
}

# Parse arguments and call corresponding function
case "$1" in
  start)
    if [ -z "$2" ]; then
      echo "Please provide a video file."
    else
      if [ -n "$3" ]; then
        type="$3"
      fi
      if [ -n "$4" ]; then
        nth_frame="$4"
      fi
      start "$2"
    fi
    ;;
  set)
    if [ -z "$2" ]; then
      echo "Please provide a directory containing images."
    else
      if [ -n "$3" ]; then
        type="$3"
      fi
      set_wallpapers "$2" &
      echo "$!" > "$PID" # Save PID to file
      echo "Livewall is now displaying wallpapers from '$2' !"
    fi
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage:"
    echo "livewall start <path to video> <image type: jpg/png> <frame interval: greater than 20 is slow>"
    echo "livewall set <images folder> <jpg/png>"
    echo "livewall stop"
    ;;
esac

exit 0
