#!/usr/bin/env bash

loc=/tmp/frames

# Save PID to file
PID="/tmp/livewall.pid"

if [ -z $3 ]; then
	type=jpg
else
	type=$3
fi
if [ -z $4 ]; then #less is fast,more is slow
	nth_frame=20
else
	nth_frame=$4
fi

function start() {
	rm -rf $loc
	if [[ -e "$1" ]]; then
		mkdir $loc
		echo 'extracting frames ...'
		ffmpeg -i $1 -r $nth_frame $loc/%d.$type &>/dev/null
		echo "Livewall started !"
		set &
		echo $! >$PID
	else
		echo "Pass a Videofile"
	fi
}

function stop() {
	if [[ -e "$PID" ]]; then
		kill -9 $(cat $PID)
		echo "Stopped livewall !"
		rm -rf $PID
	else
		echo "No livewall instance running !"
	fi
}

function set() {
	if [ $(ls $loc/ | wc -l) != 0 ]; then
		i=1
		while true; do
			feh --bg-fill $loc/$i.$type
			((i++))
			if [ $i -eq $(ls $loc/ | wc -l) ]; then
				i=1
			fi
		done
	else
		echo "Failed to find extracted images !!"
	fi
}

if [[ -z "$1" || "$1" = "-h" || "$1" = "--help" || ("$1" != "set" && "$1" != "start" && "$1" != "stop") ]]; then
	echo "Usage:"
	echo "livewall start <path to video> <image type: jpg/png> <nth frame: greater than 20 is slow >"
	echo "livewall stop"
	exit 0
fi

"$@"
