#!/bin/bash

read -p "Give video location: " vid;
read -p "Give fps count: " fps;
mkdir output;
echo 'extracting frames ...';
ffmpeg -i $vid -r $fps output/%d.png &> /dev/null;
i=1;
echo "wallsetter started !"; 
while true
do
    nitrogen output/$i.png --set-auto;
    ((i++));
    #sleep 0.01s;
    if [ $i -eq $(ls output/| wc -l) ]
    then
        i=1;
    fi
done
