#!/bin/bash

loc=/tmp/frames
function extractor(){
    rm -rf $loc;
    vid="$(ls -a | grep 'mp4\|mkv')";
    if [[ -e "$vid" ]];
    then
        read -p "Give fps count: " fps;
        mkdir $loc;
        echo 'extracting frames ...';
        ffmpeg -i $vid -r $fps $loc/%d.jpg &> /dev/null;
        setter;
    else
        echo "Copy video to this dir.";
    fi
}

function setter(){
    i=1;
    echo "wallsetter started !"; 
    while true
    do
        nitrogen $loc/$i.jpg --set-auto;
        ((i++));
        if [ $i -eq $(ls $loc/| wc -l) ]
        then
            i=1;
        fi
    done
}

"$@"
