#!/bin/bash

function extractor(){
    read -p "Give video location: " vid;
    read -p "Give fps count: " fps;
    mkdir output;
    echo 'extracting frames ...';
    ffmpeg -i $vid -r $fps output/%d.jpg &> /dev/null;
    setter;
}

function setter(){
    i=1;
    echo "wallsetter started !"; 
    while true
    do
        nitrogen output/$i.jpg --set-auto;
        ((i++));
        if [ $i -eq $(ls output/| wc -l) ]
        then
            i=1;
        fi
    done
}

"$@"
